export interface RecordedFishData {
  id: number
  name: string
  type: string
  location: string
  lure: string
  total_length: number
  weight: number
  tracking_code: string
  images: string
  date_caught: Date
}

export const fishDataArray: RecordedFishData[] = [
  {
    name: 'Buddy',
    total_length: 67,
    weight: 5.6,
    tracking_code: 'TC-TFQJA63W',
    images: '/static/images/ocean.jpeg',
    date_caught: new Date('2017-05-23T10:10:10.000Z'),
    type: 'catfish',
    location: 'pond 2',
    lure: 'spinner',
    id: 26,
  },
  {
    name: 'Whisker',
    total_length: 54,
    weight: 4.8,
    tracking_code: 'TC-2F7O1BAR',
    images: '/static/images/ocean.jpeg',
    date_caught: new Date('2020-09-25T16:16:16.000Z'),
    type: 'herring',
    location: 'pond 3',
    lure: 'jigs',
    id: 27,
  },
  {
    name: 'Slab',
    total_length: 78,
    weight: 9.2,
    tracking_code: 'TC-65AF5KXW',
    images: '/static/images/ocean.jpeg',
    date_caught: new Date('2021-10-05T17:17:17.000Z'),
    type: 'halibut',
    location: 'pond 1',
    lure: 'crank',
    id: 28,
  },
  {
    name: 'Finny',
    total_length: 134,
    weight: 13.4,
    tracking_code: 'TC-TSKHPCCD',
    images: '/static/images/ocean.jpeg',
    date_caught: new Date('2022-11-15T18:18:18.000Z'),
    type: 'tuna',
    location: 'pond 2',
    lure: 'jigs',
    id: 29,
  },
  {
    name: 'Shadow',
    total_length: 112,
    weight: 11.3,
    tracking_code: 'TC-VWALPZ56',
    images: '/static/images/ocean.jpeg',
    date_caught: new Date('2019-06-15T12:12:12.000Z'),
    type: 'barracuda',
    location: 'pond 3',
    lure: 'crank',
    id: 30,
  },
  {
    name: 'Dotty',
    total_length: 45,
    weight: 3.7,
    tracking_code: 'TC-57FLZT2X',
    images: '/static/images/ocean.jpeg',
    date_caught: new Date('2018-07-26T13:13:13.000Z'),
    type: 'perch',
    location: 'pond 1',
    lure: 'spinner',
    id: 31,
  },
  {
    name: 'Ripple',
    total_length: 87,
    weight: 7.5,
    tracking_code: 'TC-8KTP3OCY',
    images: '/static/images/ocean.jpeg',
    date_caught: new Date('2022-03-03T14:14:14.000Z'),
    type: 'mackerel',
    location: 'pond 2',
    lure: 'jigs',
    id: 32,
  },
  {
    name: 'Streak',
    total_length: 99,
    weight: 10.1,
    tracking_code: 'TC-4MHQV9G7',
    images: '/static/images/ocean.jpeg',
    date_caught: new Date('2017-10-28T15:15:15.000Z'),
    type: 'salmon',
    location: 'pond 3',
    lure: 'crank',
    id: 33,
  },
  {
    name: 'Bolt',
    total_length: 58,
    weight: 5.6,
    tracking_code: 'TC-VWALPZ56',
    images: '/static/images/ocean.jpeg',
    date_caught: new Date('2019-06-12T12:00:00.000Z'),
    type: 'trout',
    location: 'pond 1',
    lure: 'jigs',
    id: 34,
  },
  {
    name: 'Shadow',
    total_length: 115,
    weight: 11.5,
    tracking_code: 'TC-VWALPZ56',
    images: '/static/images/ocean.jpeg',
    date_caught: new Date('2020-08-18T15:00:00.000Z'),
    type: 'barracuda',
    location: 'pond 3',
    lure: 'crank',
    id: 35,
  },
  {
    name: 'Finny',
    total_length: 65,
    weight: 6.3,
    tracking_code: 'TC-57FLZT2X',
    images: '/static/images/ocean.jpeg',
    date_caught: new Date('2021-09-20T14:00:00.000Z'),
    type: 'catfish',
    location: 'pond 2',
    lure: 'spinner',
    id: 36,
  },
  {
    name: 'Dotty',
    total_length: 47,
    weight: 4.1,
    tracking_code: 'TC-57FLZT2X',
    images: '/static/images/ocean.jpeg',
    date_caught: new Date('2021-11-11T13:00:00.000Z'),
    type: 'perch',
    location: 'pond 1',
    lure: 'spinner',
    id: 37,
  },
  {
    name: 'Glide',
    total_length: 70,
    weight: 7.2,
    tracking_code: 'TC-8KTP3OCY',
    images: '/static/images/ocean.jpeg',
    date_caught: new Date('2019-12-12T16:00:00.000Z'),
    type: 'carp',
    location: 'pond 2',
    lure: 'jigs',
    id: 38,
  },
  {
    name: 'Whiskers',
    total_length: 52,
    weight: 5.1,
    tracking_code: 'TC-8KTP3OCY',
    images: '/static/images/ocean.jpeg',
    date_caught: new Date('2020-03-15T09:00:00.000Z'),
    type: 'catfish',
    location: 'pond 3',
    lure: 'jigs',
    id: 39,
  },
  {
    name: 'Blaze',
    total_length: 61,
    weight: 6.7,
    tracking_code: 'TC-9HZWDL24',
    images: '/static/images/ocean.jpeg',
    date_caught: new Date('2020-05-07T10:00:00.000Z'),
    type: 'trout',
    location: 'pond 1',
    lure: 'spinner',
    id: 40,
  },
  {
    name: 'Vortex',
    total_length: 69,
    weight: 7.0,
    tracking_code: 'TC-9HZWDL24',
    images: '/static/images/ocean.jpeg',
    date_caught: new Date('2021-07-21T17:00:00.000Z'),
    type: 'bass',
    location: 'pond 2',
    lure: 'crank',
    id: 41,
  },
  {
    name: 'Pebbles',
    total_length: 45,
    weight: 4.3,
    tracking_code: 'TC-QXNORJ5M',
    images: '/static/images/ocean.jpeg',
    date_caught: new Date('2021-04-16T08:00:00.000Z'),
    type: 'perch',
    location: 'pond 3',
    lure: 'jigs',
    id: 42,
  },
  {
    name: 'Mystic',
    total_length: 76,
    weight: 8.1,
    tracking_code: 'TC-QXNORJ5M',
    images: '/static/images/ocean.jpeg',
    date_caught: new Date('2022-02-22T12:00:00.000Z'),
    type: 'carp',
    location: 'pond 1',
    lure: 'spinner',
    id: 43,
  },
]
